# -*- coding: utf-8 -*-
"""face_detection using haarcascade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bdaQgxvBaUTdheJiA6qkxqswvAESIMOq
"""

import cv2
face_cascade = cv2.CascadeClassifier(r'haarcascade_frontalface_default.xml')

camera = cv2.VideoCapture(0,cv2.CAP_DSHOW)

while camera.isOpened():
  ret, img = camera.read()
  grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  faces = face_cascade.detectMultiScale(grey, 1.1, 4)

  for (x, y, w, h) in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (255, 0, 0), 3)

  #Display the output
  cv2.imshow('img', img)
  if cv2.waitKey(1) & 0xFF == ord('q'):
    break

camera.release()